<?php

return array(
    'title' => 'Perigest - Peritagens e Gestão de Sinistros',
    'icon' => asset('assets/images/favicon.ico'),
    'logo_title' => 'Perigest',
    'logo_img' => asset('assets/images/logo_perigest.png'),
    'template' => asset('assets/css/theme_perigest.css'),
    'copyright' => '2015 &copy; All Rights Reserved - Perigest.pt',
    'photo_default' => 'assets/images/profile/default.png',
    'photo_path' => 'assets/images/profile/',
    'from' => 'noreplay@perigest.pt',
    'from_name' => 'Perigest - Peritagens e Gestão de Sinistros',
    'reply' => 'noreplay@perigest.pt',
    'reply_name' => 'Perigest - Peritagens e Gestão de Sinistros',
    'process_folder' => storage_path() . '/processes/',
    'tmp_folder' => storage_path() . '/tmp/',
    'deadline_preliminar' => 1,
    'deadline_complete' => 30,
    'sidebar' => array(
        'home' => ['ico' => 'clip-home-3', 'roles' => [3], 'route' => 'home.index'],
        'pending.pending' => ['ico' => 'clip-bubbles', 'roles' => [3], 'route' => 'pending.index'],
        'experts.processes' => ['ico' => 'fa fa-tasks', 'roles' => [2], 'route' => 'experts.processes.index'],
        'processes' => ['ico' => 'fa fa-tasks', 'roles' => [3], 'route' => 'processes.index'],
        'processes' => ['ico' => 'fa fa-tasks', 'roles' => [3], 'route' => 'processes.index'],
        'clients' => ['ico' => 'clip-users', 'roles' => [3], 'route' => 'clients.index'],
        'insureds' => ['ico' => 'clip-users-2', 'roles' => [3], 'route' => 'insureds.index'],
        'experts' => ['ico' => 'clip-user-5', 'roles' => [3], 'route' => 'experts.index'],
        'types' => ['ico' => 'clip-tree', 'roles' => [3], 'route' => 'types.index'],
        'clients.processes' => ['ico' => 'fa fa-tasks', 'roles' => [1], 'route' => 'clients.processes.index'],
        'clients.edit.account' => ['ico' => 'fa clip-users-2 activeClass', 'roles' => [1], 'route' => 'clients.processes.account']
    ),
    'notifications' => array(
        'notifications.new_process' => ['icon' => 'fa fa-tasks', 'label' => 'label-success'],
        'notifications.new_process_ask' => ['icon' => 'fa fa-tasks', 'label' => 'label-success'],
        'notifications.new_expert' => ['icon' => 'clip-user-5', 'label' => 'label-success'],
        'notifications.new_client' => ['icon' => 'clip-users', 'label' => 'label-success'],
        'notifications.new_type' => ['icon' => 'clip-tree', 'label' => 'label-success'],
        'notifications.change_process' => ['icon' => 'fa fa-tasks', 'label' => 'label-warning'],
        'notifications.change_expert' => ['icon' => 'clip-user-5', 'label' => 'label-warning'],
        'notifications.change_client' => ['icon' => 'clip-users', 'label' => 'label-warning'],
        'notifications.change_type' => ['icon' => 'clip-tree', 'label' => 'label-warning'],
        'notifications.cancel_process' => ['icon' => 'fa fa-tasks', 'label' => 'label-danger'],
        'notifications.complete_process' => ['icon' => 'fa fa-tasks', 'label' => 'label-success'],
        'notifications.delete_expert' => ['icon' => 'clip-user-5', 'label' => 'label-danger'],
        'notifications.delete_client' => ['icon' => 'clip-users', 'label' => 'label-danger'],
        'notifications.delete_type' => ['icon' => 'clip-tree', 'label' => 'label-danger'],
        'notifications.send_process' => ['icon' => 'fa fa-tasks', 'label' => 'label-success'],
        'notifications.charge_process' => ['icon' => 'clip-checkmark-2', 'label' => 'label-success'],
        'notifications.add_invoice' => ['icon' => 'fa fa-tasks', 'label' => 'label-success'],
        'notifications.preliminar_late' => ['icon' => 'fa fa-tasks', 'label' => 'label-success'],
        'notifications.complete_late' => ['icon' => 'fa fa-tasks', 'label' => 'label-success'],
    ),
    'special_features' => array(
        'calendar' => false,
        'gallery-attachs' => false,
    ),
);

